#!/usr/bin/env ruby

require "rexml/document"

def get_version
  doc = REXML::Document.new(File.new('presentation/pom.xml'))
  doc.elements.each("project/version") { |xml| return xml.text }
end

oldpwd = Dir.pwd
version = get_version
system "chmod 600 script/pass.txt"
Dir.chdir "./presentation"
system "mvn -o -P jetty,ci-deploy,-default-dataset,-jspc -Dmaven.test.skip=true clean package"
Dir.chdir "./target/presentation-#{version}"
system "rsync -rtlv --password-file=#{oldpwd}/script/pass.txt ./library blackbox@rsync.bitgravity.com::blackbox/#{version}"
